version: '3.8'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV:-production}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG:-false}
            - DB_CONNECTION=pgsql
            - DB_HOST=${DB_HOST:-db}
            - DB_PORT=${DB_PORT:-5432}
            - DB_DATABASE=${DB_DATABASE:-your_database}
            - DB_USERNAME=${DB_USERNAME:-your_username}
            - DB_PASSWORD=${DB_PASSWORD:-your_password}
            - REDIS_HOST=${REDIS_HOST:-redis}
            - REDIS_PASSWORD=${REDIS_PASSWORD:-null}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - CACHE_DRIVER=redis
            - QUEUE_CONNECTION=redis
            - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
            - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
            - TZ=America/Sao_Paulo
        depends_on:
            - db
            - redis
            - elasticsearch
            - supervisor
        networks:
            - laravel

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

    redis:
        image: redis:latest
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis-data:/data
        networks:
            - laravel

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - laravel

    webserver:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - laravel

    supervisor:
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - ./docker/supervisor:/etc/supervisor/conf.d
        networks:
            - laravel
    laravel-echo-server:
        build:
            context: ./docker
            dockerfile: Docker.dockerfile
        ports:
            - '6001:6001'
        volumes:
            - .:/var/www/html
        networks:
            - laravel
    echo:
        image: node:14
        restart: always
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        command: bash -c "pwd && npm install -g laravel-echo-server && laravel-echo-server start"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    postgres-data:
    redis-data:
    esdata:
    supervisor:
    laravel-echo-server:
